######################################################################
# Automatically generated by qmake (3.1) Wed Sep 13 11:51:41 2017
######################################################################



MOC_DIR = build
RCC_DIR = build
OBJECTS_DIR = build

QMAKE_CFLAGS_RELEASE += -O1
QMAKE_CXXFLAGS_RELEASE += -O1
QMAKE_CPPFLAGS_RELEASE += -O1
CONFIG += QMAKE_CXXFLAGS_WARN_ON=-w
CONFIG += QMAKE_CFLAGS_WARN_ON=-w



INCLUDEPATH += $$PWD/include_cld2
DEPENDPATH += $$PWD/include_cld2

# Input
HEADERS += $$PWD/include_cld2/cld2tablesummary.h \
           $$PWD/include_cld2/cldutil.h \
           $$PWD/include_cld2/cldutil_shared.h \
           $$PWD/include_cld2/compact_lang_det.h \
           $$PWD/include_cld2/compact_lang_det_hint_code.h \
           $$PWD/include_cld2/compact_lang_det_impl.h \
           $$PWD/include_cld2/datalanguageprovider.h \
           $$PWD/include_cld2/debug.h \
           $$PWD/include_cld2/encodings.h \
           $$PWD/include_cld2/fixunicodevalue.h \
           $$PWD/include_cld2/generated_language.h \
           $$PWD/include_cld2/generated_ulscript.h \
           $$PWD/include_cld2/getonescriptspan.h \
           $$PWD/include_cld2/integral_types.h \
           $$PWD/include_cld2/lang_script.h \
           $$PWD/include_cld2/langspan.h \
           $$PWD/include_cld2/offsetmap.h \
           $$PWD/include_cld2/port.h \
           $$PWD/include_cld2/qtrlocale.h \
           $$PWD/include_cld2/scoreonescriptspan.h \
           $$PWD/include_cld2/stringpiece.h \
           $$PWD/include_cld2/tote.h \
           $$PWD/include_cld2/utf8acceptinterchange.h \
           $$PWD/include_cld2/utf8prop_lettermarkscriptnum.h \
           $$PWD/include_cld2/utf8repl_lettermarklower.h \
           $$PWD/include_cld2/utf8scannot_lettermarkspecial.h \
           $$PWD/include_cld2/utf8statetable.h
SOURCES += $$PWD/source_cld2/cld2_generated_cjk_compatible.cc \
           $$PWD/source_cld2/cld2_generated_deltaoctachrome.cc \
           $$PWD/source_cld2/cld2_generated_distinctoctachrome.cc \
           $$PWD/source_cld2/cld2_generated_quadchrome_2.cc \
           $$PWD/source_cld2/cld_generated_cjk_delta_bi_4.cc \
           $$PWD/source_cld2/cld_generated_cjk_uni_prop_80.cc \
           $$PWD/source_cld2/cld_generated_score_quad_octa_2.cc \
           $$PWD/source_cld2/cldutil.cc \
           $$PWD/source_cld2/cldutil_shared.cc \
           $$PWD/source_cld2/compact_lang_det.cc \
           $$PWD/source_cld2/compact_lang_det_hint_code.cc \
           $$PWD/source_cld2/compact_lang_det_impl.cc \
           $$PWD/source_cld2/datalanguageprovider.cpp \
           $$PWD/source_cld2/debug.cc \
           $$PWD/source_cld2/fixunicodevalue.cc \
           $$PWD/source_cld2/generated_distinct_bi_0.cc \
           $$PWD/source_cld2/generated_entities.cc \
           $$PWD/source_cld2/generated_language.cc \
           $$PWD/source_cld2/generated_ulscript.cc \
           $$PWD/source_cld2/getonescriptspan.cc \
           $$PWD/source_cld2/lang_script.cc \
           $$PWD/source_cld2/offsetmap.cc \
           $$PWD/source_cld2/qtrlocale.cpp \
           $$PWD/source_cld2/scoreonescriptspan.cc \
           $$PWD/source_cld2/tote.cc \
           $$PWD/source_cld2/utf8statetable.cc


