######################################################################
# Automatically generated by qmake (3.1) Wed Sep 13 13:00:28 2017
######################################################################



TARGET = ../../lib/qt_language_detect_api
CONFIG += qt warn_off staticlib silence
CONFIG += release

QT   += core
CONFIG += c++11
LANGUAGE	= C++
DEFINES += NDEBUG THREAD_SAFE=1 TEMP_STORE=2 WFLAGS=-Wall
TEMPLATE = lib

include(cld2.pri)
