
# Input
HEADERS += $$PWD/src/rtf-qt/TextDocumentRtfOutput.h \
           $$PWD/src/rtf-qt/AbstractRtfOutput.h \
           $$PWD/src/rtf-qt/AuthorPcdataDestination.h \
           $$PWD/src/rtf-qt/CategoryPcdataDestination.h \
           $$PWD/src/rtf-qt/ColorTableDestination.h \
           $$PWD/src/rtf-qt/CommentPcdataDestination.h \
           $$PWD/src/rtf-qt/CompanyPcdataDestination.h \
           $$PWD/src/rtf-qt/controlword.h \
           $$PWD/src/rtf-qt/Destination.h \
           $$PWD/src/rtf-qt/DocumentCommentPcdataDestination.h \
           $$PWD/src/rtf-qt/DocumentDestination.h \
           $$PWD/src/rtf-qt/FontTableDestination.h \
           $$PWD/src/rtf-qt/FontTableEntry.h \
           $$PWD/src/rtf-qt/GeneratorPcdataDestination.h \
           $$PWD/src/rtf-qt/HLinkBasePcdataDestination.h \
           $$PWD/src/rtf-qt/IgnoredDestination.h \
           $$PWD/src/rtf-qt/InfoCreatedTimeDestination.h \
           $$PWD/src/rtf-qt/InfoDestination.h \
           $$PWD/src/rtf-qt/InfoPrintedTimeDestination.h \
           $$PWD/src/rtf-qt/InfoRevisedTimeDestination.h \
           $$PWD/src/rtf-qt/InfoTimeDestination.h \
           $$PWD/src/rtf-qt/KeywordsPcdataDestination.h \
           $$PWD/src/rtf-qt/ManagerPcdataDestination.h \
           $$PWD/src/rtf-qt/OperatorPcdataDestination.h \
           $$PWD/src/rtf-qt/PcdataDestination.h \
           $$PWD/src/rtf-qt/PictDestination.h \
           $$PWD/src/rtf-qt/RtfGroupState.h \
           $$PWD/src/rtf-qt/rtfreader.h \
           $$PWD/src/rtf-qt/StyleSheetDestination.h \
           $$PWD/src/rtf-qt/StyleSheetTableEntry.h \
           $$PWD/src/rtf-qt/SubjectPcdataDestination.h \
           $$PWD/src/rtf-qt/TitlePcdataDestination.h \
           $$PWD/src/rtf-qt/Token.h \
           $$PWD/src/rtf-qt/Tokenizer.h \
           $$PWD/src/rtf-qt/UserPropsDestination.h
SOURCES += $$PWD/src/rtf-qt/TextDocumentRtfOutput.cpp \
           $$PWD/src/rtf-qt/AbstractRtfOutput.cpp \
           $$PWD/src/rtf-qt/AuthorPcdataDestination.cpp \
           $$PWD/src/rtf-qt/CategoryPcdataDestination.cpp \
           $$PWD/src/rtf-qt/ColorTableDestination.cpp \
           $$PWD/src/rtf-qt/CommentPcdataDestination.cpp \
           $$PWD/src/rtf-qt/CompanyPcdataDestination.cpp \
           $$PWD/src/rtf-qt/controlword.cpp \
           $$PWD/src/rtf-qt/Destination.cpp \
           $$PWD/src/rtf-qt/DocumentCommentPcdataDestination.cpp \
           $$PWD/src/rtf-qt/DocumentDestination.cpp \
           $$PWD/src/rtf-qt/FontTableDestination.cpp \
           $$PWD/src/rtf-qt/GeneratorPcdataDestination.cpp \
           $$PWD/src/rtf-qt/HLinkBasePcdataDestination.cpp \
           $$PWD/src/rtf-qt/IgnoredDestination.cpp \
           $$PWD/src/rtf-qt/InfoCreatedTimeDestination.cpp \
           $$PWD/src/rtf-qt/InfoDestination.cpp \
           $$PWD/src/rtf-qt/InfoPrintedTimeDestination.cpp \
           $$PWD/src/rtf-qt/InfoRevisedTimeDestination.cpp \
           $$PWD/src/rtf-qt/InfoTimeDestination.cpp \
           $$PWD/src/rtf-qt/KeywordsPcdataDestination.cpp \
           $$PWD/src/rtf-qt/ManagerPcdataDestination.cpp \
           $$PWD/src/rtf-qt/OperatorPcdataDestination.cpp \
           $$PWD/src/rtf-qt/PcdataDestination.cpp \
           $$PWD/src/rtf-qt/PictDestination.cpp \
           $$PWD/src/rtf-qt/rtfreader.cpp \
           $$PWD/src/rtf-qt/StyleSheetDestination.cpp \
           $$PWD/src/rtf-qt/SubjectPcdataDestination.cpp \
           $$PWD/src/rtf-qt/TitlePcdataDestination.cpp \
           $$PWD/src/rtf-qt/Token.cpp \
           $$PWD/src/rtf-qt/Tokenizer.cpp \
           $$PWD/src/rtf-qt/UserPropsDestination.cpp
